export const EGTS_BOT_MOD_USER_ID = 'EGTS_BOT'
export enum ModlogTypes {
    DISABLE_CHASSISID = 'DISABLE_CHASSISID',
    ENABLE_CHASSISID = 'ENABLE_CHASSISID',
    GENERATE_CHASSISID = 'GENERATE_CHASSISID',
    CREATE_CHASSIS = 'CREATE_CHASSIS',
    RENAME_CHASSIS = 'RENAME_CHASSIS',
    RESET_CHASSIS_SECRET = 'RESET_CHASSIS_SECRET',
    DELETE_CHASSISID = 'DELETE_CHASSISID',
    GIVE_DONDER = 'GIVE_DONDER',
    REMOVE_DONDER = 'REMOVE_DONDER'
}
