import {SongPlay} from "@models/queries.js";
import {createCanvas} from 'canvas';
import {getSongTitle} from "@utils/datatable.js";



export function generateScorecard(playresult: SongPlay) {

    const width = 900;
    const height = 520;

    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext('2d');

    // Background
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, width, height);

    // Text styles
    const margin = 40;
    const lineHeight = 34;

    ctx.fillStyle = '#FFFFFF';
    ctx.textBaseline = 'top';

    // Title
    ctx.font = 'bold 32px system-ui, -apple-system, Segoe UI, Roboto, Arial';
    ctx.fillText('SCORECARD', margin, margin);

    // Divider
    ctx.globalAlpha = 0.35;
    ctx.fillRect(margin, margin + 44, width - margin * 2, 2);
    ctx.globalAlpha = 1;

    const labelFont = '600 20px system-ui, -apple-system, Segoe UI, Roboto, Arial';
    const valueFont = '400 20px system-ui, -apple-system, Segoe UI, Roboto, Arial';

    const rows: Array<[string, string]> = [
        ['Song', getSongTitle(playresult.song_id, 0)],
        ['Difficulty', String(playresult.difficulty)],
        ['Score', String(playresult.score)],
        ['Score Rank', String(playresult.score_rank)],
        ['Combo', String(playresult.combo_count)],
        ['Crown', String(playresult.crown)],
        ['Drumroll', String(playresult.drumroll_count)],
        ['Good', String(playresult.good_count)],
        ['OK', String(playresult.ok_count)],
        ['Miss', String(playresult.miss_count)],
    ];

    const topY = margin + 70;
    const colGap = 60;
    const colWidth = (width - margin * 2 - colGap) / 2;

    const leftX = margin;
    const rightX = margin + colWidth + colGap;

    const mid = Math.ceil(rows.length / 2);
    // @ts-ignore
    renderColumn(ctx, rows.slice(0, mid), leftX, topY, colWidth, lineHeight, labelFont, valueFont);
    // @ts-ignore
    renderColumn(ctx, rows.slice(mid), rightX, topY, colWidth, lineHeight, labelFont, valueFont);

    ctx.globalAlpha = 0.55;
    ctx.font = '400 14px system-ui, -apple-system, Segoe UI, Roboto, Arial';
    ctx.fillText('Generated by generateScorecard()', margin, height - margin - 14);
    ctx.globalAlpha = 1;

    // Return PNG buffer
    return canvas.toBuffer('image/png');
}

function renderColumn(
    ctx: CanvasRenderingContext2D,
    rows: Array<[string, string]>,
    x: number,
    y: number,
    colWidth: number,
    lineHeight: number,
    labelFont: string,
    valueFont: string,
) {
    const labelColor = '#FFFFFF';
    const valueColor = '#FFFFFF';

    // Where values should start (align values in a neat block)
    const maxLabelWidth = Math.max(
        ...rows.map(([label]) => {
            ctx.font = labelFont;
            return ctx.measureText(label + ':').width;
        }),
    );

    const valueX = x + Math.min(maxLabelWidth + 18, colWidth * 0.55);

    let cy = y;
    for (const [label, value] of rows) {
        ctx.font = labelFont;
        ctx.fillStyle = labelColor;
        ctx.fillText(label + ':', x, cy);

        ctx.font = valueFont;
        ctx.fillStyle = valueColor;
        ctx.fillText(value, valueX, cy);

        cy += lineHeight;
    }
}